if GetLocale() == "ruRU" then
	-- general
	QulightL.option_general = "Общее"
	QulightL.option_general_uiscale = "Автоматически масштабировать интерфейс"
	QulightL.option_general_override = "Использовать раскладку для высокого разрешения при низком разрешении"
	QulightL.option_general_multisample = "Ровные края шириной 1 пиксель"
	QulightL.option_general_customuiscale = "Масштаб интерфейса (если автомасштабирование отключено)"
	QulightL.option_general_AutoRepair = "Автоматическая починка"
	QulightL.option_general_AutoGreed = "Автоматический Greed от зеленых вещей"												
	QulightL.option_general_AutoDisenchant = "Автоматический Disenchant на синьку/зеленку"	 								  		  
	QulightL.option_general_AutoDeclineDuels = "Автоматический отказ от дуэлей"	
	QulightL.option_general_AutoAcceptInvite = "Автоматический приём инвайта от друзей/гильдии"	 
	QulightL.option_general_AutoRelease = "Автоматическое воскрешение на БГ/ОЛО"	 
	QulightL.option_general_BlizzardsErrorFrameHiding = "Прятать сообщения об ошибках посреди экрана"
	QulightL.option_general_topbottompanel = "Вкл/выкл верхнию и нижнюю панельку"
	QulightL.option_general_autoinvite = "Вкл/выкл автопринятие инвайта от друзей/согильдейцев"
	QulightL.option_general_centerpanel = "Вкл/выкл центральной панели под дпс статы"
	-- Unitframes
	QulightL.option_unitframes = "Юнитфреймы"
	QulightL.option_unitframes_enable = "Включить рамки юнитов"
 	QulightL.option_unitframes_HealFrames = "Хил рейд фреймы" 
	QulightL.option_unitframes_showIndicators = "Индикаторы бафов для хил рейд фреймов" 
	QulightL.option_unitframes_showAuraWatch = "Таймеры хотов/щитов для хил рейд фреймов" 
	QulightL.option_unitframes_ShowParty = "Отображение пати в стиле рейд фреймов" 
	QulightL.option_unitframes_ShowRaid = "Включить рейд фреймы" 
	QulightL.option_unitframes_RaidShowSolo = "Включить рейд фреймы в соло" 
	QulightL.option_unitframes_RaidShowAllGroups = "Включить 6.7.8 группу в рейде" 
	QulightL.option_unitframes_enableDebuffHighlight = "Светохуйня на рейд фреймах" 
	QulightL.option_unitframes_showRaidDebuffs = "Отображение рейд дебафов" 
	QulightL.option_unitframes_showtot = "Включить цель цели" 
	QulightL.option_unitframes_showpet = "Включить пет фрейм" 
	QulightL.option_unitframes_showfocus = "Включить фокус фрейм" 
	QulightL.option_unitframes_showfocustarget = "Включить цель фокуса" 
	QulightL.option_unitframes_showBossFrames = "Включить босс фреймы" 
	QulightL.option_unitframes_TotemBars = "Включить панель тотемов для Шаманов"
	QulightL.option_unitframes_MTFrames = "Включить панели главных танков" 
	QulightL.option_unitframes_ArenaFrames = "Включить арена фреймы" 
	QulightL.option_unitframes_Reputationbar = "Включить полоску репутации" 
	QulightL.option_unitframes_Experiencebar = "Включить полоску опыта" 
	QulightL.option_unitframes_showPlayerAuras = "Использовать стандартные близз бафы/дебафы" 
	QulightL.option_unitframes_ThreatBar = "Включить полосу угрозы"
	QulightL.option_unitframes_showPortrait = "Отображать портрет на плеер и таргет фрейме"
	QulightL.option_unitframes_showRunebar = "Включить панель рун для Рыцарей Смерти"
	QulightL.option_unitframes_showHolybar = "Включить холи панель для Паладинов" 
	QulightL.option_unitframes_showEclipsebar = "Включить экслипс панель для Баланс Друидов" 
	QulightL.option_unitframes_showShardbar = "Включить панель для шардов для Варлоков" 
	QulightL.option_unitframes_RCheckIcon = "Включить иконки Готовности на рейд фреймах" 
	QulightL.option_unitframes_Castbars = "Включить кастбары" 
	QulightL.option_unitframes_showLFDIcons = "Включить лфг иконки" 
	QulightL.option_unitframes_HealthcolorClass = "Панель жыызней под цвет класса"
	QulightL.option_unitframes_Powercolor = "Повер панель под цвет типа повера %)"
	QulightL.option_unitframes_showPartyFrames = " Отображение пати фреймов"
	QulightL.option_unitframes_bigcastbar = "Большой кастбар"
	
	--raidframes
	QulightL.option_raidframes = "Рейд фреймы"
	QulightL.option_raidframes_aggro_border = "Отображение угрозы"
	QulightL.option_raidframes_deficit_health = "Значение здоровья по дефициту"
	QulightL.option_raidframes_power = "Отображение панели маны"
	QulightL.option_raidframes_vertical_health = "Вертикальное направление полосы здоровья"
	QulightL.option_raidframes_alpha_health = "Прозрачность полосы здоровья, если 100%"
	QulightL.option_raidframes_show_range = "Прозрачность рамок вне зоны досягаемости"
	QulightL.option_raidframes_range_alpha = "Значение для прозрачности рамок вне зоны досягаемости"
	QulightL.option_raidframes_hp_value = "Отображение хп текса"
	QulightL.option_raidframes_width = "Ширина рейд фрейма"
	QulightL.option_raidframes_height = "Высота рейд фрейма"
	QulightL.option_raidframes_show_party = "Отображать рамки группы"
	QulightL.option_raidframes_show_raid = "Отображать рамки рейда"
	QulightL.option_raidframes_solo_mode = "Всегда отображать рамку игрока"
	QulightL.option_raidframes_player_in_party = "Отображать рамку игрока в группе"
	QulightL.option_raidframes_raid_groups = "Количество групп в рейде"
	QulightL.option_raidframes_raid_groups_vertical = "Группы рейда вертикально"
	QulightL.option_raidframes_icons_role = "Отображать иконку роли"
	QulightL.option_raidframes_icons_raid_mark = "Отображать рейдовые метки"
	QulightL.option_raidframes_icons_ready_check = "Отображать иконки готовности"
	QulightL.option_raidframes_icons_leader = "Отображать иконки лидера, помощника и ответственного за добычу"
	QulightL.option_raidframes_plugins_debuffhighlight_icon = "Иконка + текстура снимаемых отрицательных эффектов"
	QulightL.option_raidframes_plugins_aura_watch = "Отображать рейдовые отрицательные эффекты"
	QulightL.option_raidframes_plugins_aura_watch_timer = "Таймер на отрицательных эффектах"
	QulightL.option_raidframes_plugins_healcomm = "Отображать поступающее лечение"
	QulightL.option_raidframes_plugins_auto_resurrection = "Автовоскрешение средней кнопкой мыши (не работает с Clique)"
	QulightL.option_raidframes_own_color = "Использовать свой цвет для полос здоровья"
	QulightL.option_raidframes_fontsize = "Размер шрифта"
    QulightL.option_raidframes_fontsizeEdge = "хз"
    QulightL.option_raidframes_outline = "Стиль шрифта"
	QulightL.option_raidframes_bar_color_value = "Цвет полосы здоровья по его значению"
	QulightL.option_raidframes_color_value = "Цветное значение здоровья/энергии"
	QulightL.option_raidframes_plugins_smooth_bar = "Плавное изменение полос"
	QulightL.option_raidframes_show_timer = "Отображать таймер перезарядки аур"
	QulightL.option_raidframes_show_spiral = "Спираль перезарядки на аурах"
	QulightL.option_raidframes_debuff_color_type = "Цвета краёв отрицательных эффектов по их типу"
	
	--media
	QulightL.option_media = "Media" 	
	QulightL.option_media_font = "Основной шрифт для Qulight UI" 
	QulightL.option_media_pxfont = "1 px шрифт для Qulight UI" 
	QulightL.option_media_fontsize = "Размер шрифта" 
	QulightL.option_media_bordercolor = "Цвет бордюров" 
	QulightL.option_media_backdropcolor = "Цвет фона" 
	QulightL.option_media_texture = "Тектура для полосок" 
	QulightL.option_media_blank = "Текстура для фона" 
	--bags
	QulightL.option_bags = "Cумки"	
	QulightL.option_bags_Enable = "Включить сумки"
	QulightL.option_bags_BagBars = "Включить панель сумок"
	--datatext
	QulightL.option_datatext = "Текст панелей"
	QulightL.option_datatext_Durability = "Прочность"
	QulightL.option_datatext_System = "Память/ФПС/Пинг"
	QulightL.option_datatext_Gold = "Золото"
	QulightL.option_datatext_Guild = "Гильдия"
	QulightL.option_datatext_Friends = "Друзья"
	QulightL.option_datatext_specswitcher = "Менялка билда"
	QulightL.option_datatext_Bags = "Сумки"
	QulightL.option_datatext_Wowtime = "Время"
	QulightL.option_datatext_Togglemenu = "МиниМеню"
	QulightL.option_datatext_Time24 = "24-часовой формат времени"
	QulightL.option_datatext_Localtime = "Использовать локальное время вместо серверного"
	QulightL.option_datatext_classcolor = "Включить цвет текста под цвет класса"
	QulightL.option_datatext_color = "Если цвет текста под цвет класса выключен, то выберите цвет:"
	--loot
	QulightL.option_loot = "Лут"
	QulightL.option_loot_lootframe = "Включить окно добычи"
	QulightL.option_loot_rolllootframe = "Включить окно розыгрыша"
	QulightL.option_loot_position = "Позиция окна розыгрыша"
	--misk
	QulightL.option_enable = "Включить" 
	QulightL.option_addonmanager = "Аддон менеджер" 
	QulightL.option_togglemenu = "МиниМеню" 
	QulightL.option_togglemenu_buttonwidth = "Ширина кнопок" 
	QulightL.option_togglemenu_buttonheight = "Высота кнопок" 
	QulightL.option_togglemenu_classcolor = "Включить рамки под цвет класса" 
	QulightL.option_classtimer = "КлассТаймер" 
	QulightL.option_cooldown = "Кулдауны" 
	QulightL.option_skinframe = "Близскин" 	
	QulightL.option_filger = "Филгер" 
	QulightL.option_Threatbar = "Полоска угрозы" 
	--chat
	QulightL.option_chat = "Чат"
	QulightL.option_chat_enable = "Включить"
	QulightL.option_chat_chatbar= "Включить чат бар(кнопки для каналов)" 
	QulightL.option_chat_chatframewidth = "Ширина чата"
	QulightL.option_chat_chatframeheight = "Высота чата"
	QulightL.option_chat_editboxwidth = "Ширина поля ввода текста"
	QulightL.option_chat_editboxheight = "Высота поля ввода текста"
	QulightL.option_chat_tabtextcolor = "Цвет закладок чата"
	QulightL.option_chat_ChatFrame = "Позиция чата"
    --buffs
	QulightL.option_buffs = "Бафы/Дебафы"
	QulightL.option_buffs_enable = "Включить"
	QulightL.option_buffs_iconsize = "Размер бафов"
	QulightL.option_buffs_iconsizede = "Размер дебафов"
	QulightL.option_buffs_timefontsize = "Размер шрифта времени"
	QulightL.option_buffs_countfontsize = "Размер шрифта стаков" 
	QulightL.option_buffs_spacing = "Интервал между бафами" 
	QulightL.option_buffs_debuffspacing = "Интервал между дебафами" 
	QulightL.option_buffs_timeYoffset = "Отступ по вертикали" 
	QulightL.option_buffs_BUFFS_PER_ROW = "Количество бафов в ряду" 
	--addonskinning
	QulightL.option_addonsskins = "Скининг Аддонов"
	QulightL.option_addonsskins_DBM = "DBM(/dbmskin apply)"
	QulightL.option_addonsskins_PallyPower = "PallyPower" 
	QulightL.option_addonsskins_Skada = "Skada" 
	QulightL.option_addonsskins_Recount = "Recount"
	QulightL.option_addonsskins_Omen = "Omen"
	QulightL.option_addonsskins_KLE = "KLE"	
	QulightL.option_addonsskins_Quartz = "Quartz"		
	QulightL.option_addonsskins_Bigwigs = "Bigwigs(/bigwigstest apply)"
	QulightL.option_addonsskins_DXE = "DXE(Deus Vox Encounters)"
	
	
	--nameplates
	QulightL.option_nameplates = "Неймплейты"
	QulightL.option_nameplates_enable  = "Включить неймплейты"
	QulightL.option_nameplates_showlevel = "Отображать уровень на неймплейтах"
	QulightL.option_nameplates_width = "Ширина неймплейтов"
	QulightL.option_nameplates_showhealth = "Отобжать уровень жизней"
	QulightL.option_nameplates_enhancethreat = "Перекрашивать цвет неймплейтов в зависимости от агро"
	QulightL.option_nameplates_combat = "Только в бою"
	QulightL.option_nameplates_goodcolor = "Хороший цвет угрозы"
	QulightL.option_nameplates_badcolor = "Плохой цвет угрозы"
	QulightL.option_nameplates_goodtransitioncolor = "Хороший переходной цвет угрозы"
	QulightL.option_nameplates_badtransitioncolor = "Плохой переходной цвет угрозы"
	QulightL.option_nameplates_trackauras = "Отображать ваши дебаффы на индикаторах здоровья."
	QulightL.option_nameplates_trackccauras = "Отображать CC дебаффы на вашем индикаторе здоровья или на индикаторах союзников"
	QulightL.option_nameplates_aurasize = "Размер дебафов"
	QulightL.option_nameplates_height = "Высота неймплейтов"
	
	QulightL.option_Minimap = "Минимапа"
	QulightL.option_Minimapenable = "Включить"
	QulightL.option_Minimapminimapsize = "Размер Минимапы"
	QulightL.option_Map = "Карта"
	QulightL.option_mapenable = "Включить"
		
	QulightL.option_tooltip = "Тултип"
	QulightL.option_tooltip_enable = "Включить подсказку"
	QulightL.option_tooltip_hidecombat = "Прятать подсказку в бою"
	QulightL.option_tooltip_hidebuttons = "Прятать подсказку для кнопок панели действий"
	QulightL.option_tooltip_hideuf = "Прятать подсказку для рамок юнитов"
	QulightL.option_tooltip_cursor = "Подсказка под указателем мыши"
	QulightL.option_tooltip_itemlevel = "Отображать уровень предмета"
	QulightL.option_tooltip_spellid = "Отображать спелл ид"
	QulightL.option_tooltip_talents = "Отображать таланты цели на тултипе"
	QulightL.option_markbar = "Панель меток"
	QulightL.option_markbarenable = "Включить панель меток"
	
	-- action bar
	QulightL.option_actionbar = "Панели кнопок"
	QulightL.option_actionbar_enable = "Включить панели кнопок"
	QulightL.option_actionbar_hotkey = "Отображать назначений клавишь на кнопках"
	QulightL.option_actionbar_hideSTANCE = "Скрыть шифтбар(тотемы, аспекты, ауры, стойки, формы)"
	QulightL.option_actionbar_bottomrows = "Главные панели (1-3)"
	QulightL.option_actionbar_rightbars = "Правые панели (0-3)"
	QulightL.option_actionbar_splitbar = "Боковые панели от главных"
	QulightL.option_actionbar_buttonsize = "Размер кнопок"
	QulightL.option_actionbar_buttonspacing = "Отступ между кнопками"
	QulightL.option_actionbar_petbuttonsize = "Размер кнопок пета"
	QulightL.option_actionbar_petbuttonspacing = "Отступ между пет кнопками"
	QulightL.option_actionbar_swaptopbottombar = "Поменять местами бар1 и бар2"
	QulightL.option_actionbar_macrotext = "Отображать текст макросов на кнопках"
	QulightL.option_actionbar_verticalshapeshift = "Вертикальное положение шифт бара"
	QulightL.option_actionbar_microbar = "Микро панель"
	QulightL.option_actionbar_mousemicro = "Микро панель по маузоверу"
	QulightL.option_actionbar_showgrid = "Отображать пустые слоты кнопок"
	QulightL.option_actionbar_mainbarWidth = "Количество кнопок у основных центральных панелей(1-12)"
	QulightL.option_actionbar_ownshdbar = "Использовать пустую панель для танца теней (разбойник) вместо панели невидимости"
	QulightL.option_actionbar_lowversion = "Другая версия экшен баров"
	QulightL.option_actionbar_sidebarWidth = "Количество кнопок у боковых панелей, данная опция работает если Другая версия экшен баров отключена"
	
	QulightL.option_misk = "Разное"
	QulightL.option_raidutility = "Утилиты для рейда"
	QulightL.option_BuffReminderRaidBuffs = "Панель рейд бафов на игроке(Напоминалка)"
	QulightL.option_Reminder = "Панель соло бафов на игроке(Напоминалка)"
	QulightL.option_CooldownFlash = "Иконко всплывалко"
	QulightL.option_interrupts = "Аннос прерывание каста игрока в /say"
	QulightL.option_AutoScreen = "Автоматическая скринилка при получении ачива"
	
	QulightL.option_reset = "Сбросить"
	QulightL.option_apply = "Применить"
	QulightL.option_close = "Закрыть"
	QulightL.option_setsavedsetttings = "Установить настройки для персонажа"
	QulightL.option_resetchar = "Вы уверены, что хотите сбросить все настройки для персонажа до настроек по умолчанию?"
	QulightL.option_resetall = "Вы уверены, что хотите сбросить все настройки?"
	QulightL.option_perchar = "Вы уверены что хотите сменить режим сохранения настроек?"
	QulightL.option_makeselection = "Вы должны сделать выбор прежде чем продолжите конфигурацию"
	
	
	QulightL.option_bottombars = "Колиство полос боттом баров(по центру снизу)"
	QulightL.option_nameplates_showlevel = "Отображать уровень"
	QulightL.option_raidcooldowns = "Рейд кулдауны(батлресы, героизмы, анхи итд)"
	QulightL.option_DamagebarWidth = "Количество кнопок у демаг бара(1-12)"
	QulightL.option_Damagebar = "Включить демаг бар"
	QulightL.option_rightbars = "Правая панель(если выключена то включается демагбар)"
 	QulightL.option_sidebars = "Боковые панели"
end